git:
  commit:
    # If true, pass '--signoff' flag when committing
    signOff: true

# If true, display a confirmation when subprocess terminates. This allows you to
# view the output of the subprocess before returning to Lazygit.
promptToReturnFromSubprocess: false
