packadd! coc.nvim
packadd! helptoc
packadd! lightline.vim
packadd! markdown-preview.nvim
packadd! nerdtree
packadd! ultisnips
packadd! vim-devicons
packadd! vim-go
packadd! vim-nix
packadd! vim-snippets
