syntax enable

"set autochdir
set autoindent
set autoread
set background=dark
set backspace=indent,eol,start
set belloff=all
set breakindent
set colorcolumn=80
if has('patch-9.0.0000') | set completeopt+=fuzzy | endif
set confirm
set cursorline
set display=lastline
set encoding=utf-8
set expandtab
set foldcolumn=1
set foldenable
set foldlevel=99
set foldlevelstart=99
set foldmethod=indent
set formatoptions=rqnl1j
set history=10000
set hlsearch
set ignorecase
set incsearch
set infercase
set laststatus=2
set linebreak
set list
set listchars=tab:>\ ,trail:-,nbsp:+
set mat=1
set mouse=a
set nobackup
set noerrorbells
set nojoinspaces
set noshowmode
set nostartofline
set noswapfile
set novisualbell
set nowrap
set nowritebackup
set number
set omnifunc=syntaxcomplete#Complete
set pumheight=10
set noruler
set scrolloff=10
set shiftround
set shiftwidth=4
set showcmd
set showmatch
set signcolumn=yes
set smartcase
set smarttab
set splitbelow
set splitright
set switchbuf=uselast
set t_vb=
set tabstop=4
set termguicolors
set textwidth=80
set timeoutlen=300
set undodir=$HOME/.local/state/vim/undo
set undofile
set viewdir=$HOME/.local/state/vim/view
set updatetime=250
set virtualedit=block
set wildmenu
if has('patch-9.0.0670') | set wildoptions+=fuzzy | endif

" 8. Command-line autocompletion                         *cmdline-autocompletion*
if exists('*wildtrigger')
  let s:wt_timer = -1
  function! s:WildtriggerDebounced() abort
    if s:wt_timer != -1
      call timer_stop(s:wt_timer)
    endif
    let s:wt_timer = timer_start(150, {-> wildtrigger()})
  endfunction
  autocmd CmdlineChanged [:\/\?] call s:WildtriggerDebounced()
  set wildmode=noselect:lastused,full
  set wildoptions+=pum
endif

let &t_EI = "\e[2 q"
let &t_SI = "\e[6 q"
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
let mapleader = " "
let maplocalleader = ","

let s:grep_exclude_dirs = ['.git', 'node_modules', '.cache', 'dist', 'build']

if executable('rg')
  set grepprg=rg\ --vimgrep\ --smart-case
  set grepformat=%f:%l:%c:%m
elseif executable('git')
  let &grepprg = 'git grep -n $*'
  set grepformat=%f:%l:%m
else
  let &grepprg = 'LC_ALL=C grep -rn '
    \ . join(map(copy(s:grep_exclude_dirs), '"--exclude-dir=" . v:val'), ' ')
    \ . ' $*'
  set grepformat=%f:%l:%m
endif

set wildignore+=*.o,*.pyc,*/.git/*,*/node_modules/*,*/dist/*,*/build/*

inoremap JK <Esc>
inoremap Jk <Esc>
inoremap jK <Esc>
inoremap jk <Esc>
nnoremap <silent> <Leader>l :nohl<CR>
nnoremap <Leader>mm :make<CR>
nnoremap <Leader>so :source $HOME/.config/vim/vimrc<CR>

nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

filetype plugin indent on

"Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
                  \ if line("'\"") > 0 && line("'\"") <= line("$") |
                  \   exe "normal! g`\"" |
                  \ endif

autocmd FocusGained,BufEnter * if getcmdwintype() == '' | checktime | endif

autocmd BufWinLeave,BufWritePost,WinLeave *
                  \ if get(b:, 'view_activated') | silent! mkview | endif
autocmd BufWinEnter *
                  \ if !get(b:, 'view_activated') && &buftype == '' && &filetype != '' |
                  \   let b:view_activated = 1 | silent! loadview | endif

source $HOME/.config/vim/colors.vim
source $HOME/.config/vim/plugins.vim

"Optional plugins (highly recommended)
"These are generally available in package managers.
"```
"Discover plugins
"dnf search vim
"```
"
"To see what the runtime path for plugin discovery is. I recommend using `tree`
"to find these files.
"```
":set runtimepath
"```
"To disable certain paths,
"```
":set runtimepath-=~/.vim/bundle/vimacs
"```
"
"or find the 'enable' line and manually 'disable' individual plugins. note, it
"is set to 1 not 0 (weird).
"```
"let g:loaded_ctrlp = 1
"```
"
"alternatively, create folders under ~/.vim/pack
"mkdir -p ~/.vim/pack/{color,syntax,plugins}/{opt/start}
"clone in repositories under the opt (for optional) and start (for required)
"git -C https://github.com/tpope/vim-commentary clone ~/.vim/pack/plugins/start
"
"for optional packages, use :packadd to include them
"
"add plugin configuration under .vim/after/plugin/
