filetype plugin indent on
syntax enable

"set autochdir
set autoindent
set autoread
set background=dark
set backspace=indent,eol,start
set belloff=all
set breakindent
set colorcolumn=80
if exists('+autocomplete') | set autocomplete | endif
try | set complete=.^5,w^5,b^5,u^5 | catch | set complete=.,w,b,u | endtry
set completeopt=menu,preview,menuone,noinsert,noselect
try | set completeopt+=popup,fuzzy | catch | endtry
set confirm
set cursorline
set display=lastline
set encoding=utf-8
set expandtab
set exrc
set foldcolumn=1
set foldenable
set foldlevel=99
set foldlevelstart=99
set foldmethod=indent
set formatoptions=rqnl1j
set history=10000
set hlsearch
set ignorecase
set incsearch
set infercase
set laststatus=2
set linebreak
set list
set listchars=tab:>\ ,trail:-,nbsp:+
set mat=1
set mouse=a
set nobackup
set noerrorbells
set nojoinspaces
set noshowmode
set nostartofline
set noswapfile
set novisualbell
set nowrap
set nowritebackup
set number
set omnifunc=syntaxcomplete#Complete
set pumheight=10
set noruler
set scrolloff=10
set secure
set shiftround
set shiftwidth=4
set showcmd
set showmatch
set signcolumn=yes
set smartcase
set smarttab
set splitbelow
set splitright
try | set switchbuf=uselast | catch | endtry
set t_vb=
set tabstop=4
if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
set textwidth=80
set timeoutlen=300
set undodir=$HOME/.local/state/vim/undo
set undofile
set viewdir=$HOME/.local/state/vim/view
set viminfofile=$HOME/.local/state/vim/viminfo
set updatetime=250
set virtualedit=block
set path=.,,
set wildmenu
try | set wildoptions+=fuzzy | catch | endtry

let s:in_git_repo = executable('git') && (!empty(finddir('.git', '.;')) || !empty(findfile('.git', '.;')))

"show autocompletion help for the command line mode
if exists('*wildtrigger')
  augroup wildtrigger
    autocmd!
    autocmd CmdlineChanged [:\/\?] call wildtrigger()
  augroup END
  set wildmode=noselect:lastused,full
  set wildoptions+=pum
endif

let &t_EI = "\e[2 q"
let &t_SI = "\e[6 q"
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
let mapleader = " "
let maplocalleader = ","

let s:exclude_dirs = [
  \ '.git',
  \ 'node_modules',
  \ '.cache',
  \ 'dist',
  \ 'build',
  \ '_build',
  \ '.direnv',
  \ 'pack',
  \ 'view',
  \ 'venv',
  \ ]

let s:exclude_files = [
  \ '*.lock',
  \ ]

let s:gitexc = join(map(copy(s:exclude_dirs) + copy(s:exclude_files), 'shellescape(":(exclude)" . v:val)'), ' ')
let s:grepexc = join(map(copy(s:exclude_dirs), '"--exclude-dir=" . shellescape(v:val)'), ' ')
  \ . ' ' . join(map(copy(s:exclude_files), '"--exclude=" . shellescape(v:val)'), ' ')

"better find function
if exists('+findfunc')
    " NOTE: if has ripgrep or fd_find, then use
    " \ : executable('fd') ? 'fd --type f'
    " \ : executable('rg') ? 'rg --files'
  let s:findcmd = s:in_git_repo ? 'git ls-files -co --deduplicate --exclude-standard -- . ' . s:gitexc
    \ : 'find . -type f'
  let s:filescache = []
  func! FindFiles(arg, _)
    if empty(s:filescache)
      let s:filescache = systemlist(s:findcmd)
      if s:in_git_repo | call filter(s:filescache, 'filereadable(v:val)') | endif
    endif
    return empty(a:arg) ? s:filescache : matchfuzzy(s:filescache, a:arg)
  endfunc
  set findfunc=FindFiles
  autocmd CmdlineEnter : let s:filescache = []
endif

"better grep function
" NOTE: if has ripgrep
" \ : executable('rg') ? 'rg --vimgrep ' . ' $*'
let &grepprg = s:in_git_repo ? 'git grep --untracked -n $* -- ' . s:gitexc
  \ : 'LC_ALL=C grep -rn ' . s:grepexc . ' $*'
set grepformat=%f:%l:%c:%m,%f:%l:%m

"live fuzzy grep picker + auto-pick on <CR> (requires Vim 9.1)
if exists('*cmdcomplete_info') && exists('##CmdlineLeavePre')
  command! -nargs=+ -complete=customlist,<SID>Grep
    \ Grep call <SID>VisitFile()

  func s:Grep(arglead, cmdline, cursorpos)
    if match(&grepprg, '\$\*') == -1 | let &grepprg ..= ' $*' | endif
    let cmd = substitute(&grepprg, '\$\*', shellescape(escape(a:arglead, '\')), '')
    return len(a:arglead) > 1 ? systemlist(cmd) : []
  endfunc

  func s:VisitFile()
    let item = getqflist(#{lines: [s:selected]}).items[0]
    let pos  = '[0,\ item.lnum,\ item.col,\ 0]'
    exe $':b +call\ setpos(".",\ {pos}) {item.bufnr}'
    call setbufvar(item.bufnr, '&buflisted', 1)
  endfunc

  autocmd CmdlineLeavePre :
    \ if get(cmdcomplete_info(), 'matches', []) != [] |
    \   let s:info = cmdcomplete_info() |
    \   if getcmdline() =~ '^\s*fin\%[d]\s' && s:info.selected == -1 |
    \     call setcmdline($'find {s:info.matches[0]}') |
    \   endif |
    \   if getcmdline() =~ '^\s*Grep\s' |
    \     let s:selected = s:info.selected != -1
    \         ? s:info.matches[s:info.selected] : s:info.matches[0] |
    \     call setcmdline(s:info.cmdline_orig) |
    \   endif |
    \ endif
endif

set wildignore+=*.o,*.pyc
execute 'set wildignore+=' . join(map(copy(s:exclude_dirs), '"*/" . v:val'), ',')

inoremap JK <Esc>
inoremap Jk <Esc>
inoremap jK <Esc>
inoremap jk <Esc>
nnoremap - :Ex<CR>
nnoremap <silent> <Leader>l :nohl<CR>
nnoremap <Leader>mm :make<CR>
nnoremap <Leader>so :source $HOME/.config/vim/vimrc<CR>

nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

augroup vimrc
  autocmd!
  "Return to last edit position when opening files
  autocmd BufReadPost *
                    \ if line("'\"") > 0 && line("'\"") <= line("$") |
                    \   exe "normal! g`\"" |
                    \ endif
  autocmd FocusGained,BufEnter * if getcmdwintype() == '' | checktime | endif
augroup END

source $HOME/.config/vim/colors.vim
source $HOME/.config/vim/builtin.vim
source $HOME/.config/vim/plugins.vim

"Optional plugins (highly recommended)
"These are generally available in package managers.
"```
"Discover plugins
"dnf search vim
"```
"
"To see what the runtime path for plugin discovery is. I recommend using `tree`
"to find these files.
"```
":set runtimepath
"```
"To disable certain paths,
"```
":set runtimepath-=~/.vim/bundle/vimacs
"```
"
"or find the 'enable' line and manually 'disable' individual plugins. note, it
"is set to 1 not 0 (weird).
"```
"let g:loaded_ctrlp = 1
"```
"
"alternatively, create folders under ~/.vim/pack
"mkdir -p ~/.vim/pack/{color,syntax,plugins}/{opt/start}
"clone in repositories under the opt (for optional) and start (for required)
"git -C https://github.com/tpope/vim-commentary clone ~/.vim/pack/plugins/start
"
"for optional packages, use :packadd to include them
"
"add plugin configuration under .vim/after/plugin/
